[Polytope] Add basic plot recipe for polytopes
zerefwayne/MeshesRecipes.jl pull request #2
Opened 2020-11-26 23:07 UTC by zerefwayne

2020-11-28 10:38 UTC, juliohm requested changes
It is nice to see this work getting started. After you fix these issues, please consider adding a README with a simple example of usage.

2020-11-28 10:38 UTC, juliohm commented on src/polytypes.jl
> +function default_theme(scene::SceneLike, ::Type{<: Plot(Polytope)})
Extra space after `<:`

2020-11-28 10:38 UTC, juliohm commented on src/polytypes.jl
> +        color = :red,
Let's keep things simple, `color=:black` by default seems more neutral.

2020-11-28 10:38 UTC, juliohm commented on src/polytypes.jl
> +    poly!(plot, v, color = :transparent, strokecolor = plot[:color], strokewidth = plot[:strokewidth])
Awesome. As we discussed, it would be nice to replace `poly!` by some primitive recipe.

2020-12-07 15:55 UTC, zerefwayne commented
### 2D Polytope

![image](https://user-images.githubusercontent.com/28949397/101373208-b53ea000-38d2-11eb-89e8-b5b2f462de65.png)

### 3D Polytope

![image](https://user-images.githubusercontent.com/28949397/101373271-c4bde900-38d2-11eb-8657-6477246257fa.png)

2020-12-07 16:02 UTC, juliohm requested changes

2020-12-07 16:02 UTC, juliohm commented on src/polytypes.jl
> +        lines!(plot, xs, ys)
So is this the basic building block? isn't it `linesegments!`?

Also, I think we don't want to create segments like this. We want to take the edges of the polytope with `edges = facets(pt)` and then plot each segment:

```julia
for e in edges
  u, v = coordinates.(vertices(e))
  linesegments!(plot, u, v)
end
```
or something like that.

2020-12-07 16:02 UTC, juliohm commented on src/polytypes.jl
> +    end
I think the code will be agnostic to the dimension if you use the linesegments approach we discussed some time ago. I don't understand why you used `lines!` here.

2020-12-15 11:55 UTC, juliohm requested changes

2020-12-15 11:55 UTC, juliohm commented on src/MeshesRecipes.jl
> +import AbstractPlotting: Plot, default_theme, plot!, to_value
Add a blank line before the import, it is nice to separate using from import statements

2020-12-15 11:55 UTC, juliohm commented on src/polytypes.jl
> +end
Mind using 2 whitespaces for indentation to follow Meshes.jl conventions?

2020-12-15 11:55 UTC, juliohm commented on src/polytypes.jl
> +"""
A simpler docstring would be:

>Function to plot general Polytope objects.

2020-12-15 11:55 UTC, juliohm commented on src/polytypes.jl
> +    end
We can generalize this logic to N-dimensional polytopes. You are typing "edge" and "vertices" etc, but this only applies to Polygon = Polytope{2}. In the case of a Polyhedra = Polygon{3} the facets are "areas" or triangles to be plotted.

Perhaps this function should be generalized with a recursion or you should break it into two methods one for 2D Polygon and another for 3D Polyhedra. Makes sense?

I like the code very much though, much cleaner than Plots.jl recipes in general.

2020-12-15 14:27 UTC, zerefwayne commented on src/polytypes.jl
> +    end
For now, I tested polytopes in 2D & 3D spaces and the code functions well. I'll try to create a separate function for polyhedras in the next PR.

2020-12-15 15:14 UTC, juliohm approved these changes

2020-12-15 15:14 UTC, merged